name = "fremdmaps"
main = "worker/index.ts"
compatibility_date = "2026-06-16"

[assets]
binding = "ASSETS"
directory = "client/dist"
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
